import json
from collections import defaultdict
from typing import List, Dict, Any, Optional
from config import settings

class EnrichmentService:
    """
    Service to load and query enrichment data (Co-purchase, Margin, Velocity).
    Data is sourced from a local JSON artifact generated by BigQuery.
    """

    def __init__(self, data_path: Optional[str] = None):
        self.data_path = data_path or (settings.DATA_DIR / "enrichment_data.json")
        self.item_map = defaultdict(list)
        self.category_map = defaultdict(list)
        self._load_data()

    def _load_data(self):
        """Load JSON artifact and build lookup maps."""
        try:
            with open(self.data_path, "r") as f:
                data = json.load(f)
                
            # Index Item-Item
            for row in data.get("item_cooccurrence", []):
                source_sku = row.get("source_sku")
                if source_sku:
                    self.item_map[source_sku].append(row)

            # Index Category-Item
            for row in data.get("category_cooccurrence", []):
                cat_id = row.get("category_id")
                if cat_id:
                    self.category_map[cat_id].append(row)
                    
        except FileNotFoundError:
            print(f"⚠️ Warning: Enrichment data not found at {self.data_path}. Running without enrichment.")
        except json.JSONDecodeError:
            print(f"⚠️ Error: Enrichment data at {self.data_path} is invalid JSON.")

    def get_item_recommendations(self, sku: str) -> List[Dict[str, Any]]:
        """
        Get items frequently co-purchased with the given SKU.
        Returns list of dicts with keys: rec_sku, copurchase_count, rec_velocity, rec_margin, etc.
        """
        return sorted(
            self.item_map.get(sku, []),
            key=lambda x: x.get("copurchase_count", 0),
            reverse=True
        )

    def get_category_recommendations(self, category_id: int) -> List[Dict[str, Any]]:
        """
        Get items frequently co-purchased with items in the given category.
        """
        return sorted(
            self.category_map.get(category_id, []),
            key=lambda x: x.get("copurchase_count", 0),
            reverse=True
        )

    def get_enrichment_for_pair(self, source_sku: str, target_sku: str) -> Optional[Dict[str, Any]]:
        """
        Find specific co-purchase stats for a Source -> Target pair.
        """
        candidates = self.item_map.get(source_sku, [])
        for c in candidates:
            if c.get("rec_sku") == target_sku:
                return c
        return None
